general {
    grab_focus = 1
}

cache {
    enabled = 1
}

finders {
    default_finder = desktop
    unicode_prefix = .
    math_prefix = =
}

display {
    show_descriptions = 1
    show_paths = 0
    show_icons = 1
    show_search = 1
    show_actions = 1
}
