theme {
    color_scheme = ~/.local/share/color-schemes/CatppuccinMochaLavender.colors
    icon_theme = Catppuccin-Mocha-Lavender-Cursors
    style = kvantum
    font = JetBrainsMono Nerd Font
    font_size = 10
    font_fixed = JetBrainsMono Nerd Font Mono
    font_fixed_size = 10
}
